configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/xjtu-yeanhua/everos-trial-c326c83e72f12a3ae9515a234d1817f5ce6241f25f9bb6590321b9c85df95eb6.yml
openapi_spec_hash: f2e3cb23ef91bf5ba9ecb88e3d00da76
config_hash: a08d519d91bb47fef69cb55e5f5dcfdd
